version: "3.9"
services:
  mumbai-node-1:
    container_name: mumbai-node-1
    image: mongo
    command: mongod --shardsvr --replSet mum --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    networks:
      - mumbai
  mumbai-node-2:
    container_name: mumbai-node-2
    image: mongo
    command: mongod --shardsvr --replSet mum --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    networks:
      - mumbai
  mumbai-node-3:
    container_name: mumbai-node-3
    image: mongo
    command: mongod --shardsvr --replSet mum --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    networks:
      - mumbai
networks:
  mumbai:
    name: "mumbai"

