version: "3.9"
services:
  delhi-node-1:
    container_name: delhi-node-1
    image: mongo
    command: mongod --replSet dl --port 27017 --dbpath /data/mongo
    ports:
      - 30001:27017
    networks:
      - kolkata
  delhi-node-2:
    container_name: delhi-node-2
    image: mongo
    command: mongod --replSet dl --port 27017 --dbpath /data/mongo
    ports:
      - 30002:27017
    networks:
      - kolkata
  delhi-node-3:
    container_name: delhi-node-3
    image: mongo
    command: mongod --replSet dl --port 27017 --dbpath /data/mongo
    ports:
      - 30003:27017
    networks:
      - kolkata
