version: "3.9"
services:
  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfsvr/config-server-1:27017,config-server-2:27017,config-server-3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27017:27017
    networks:
      - mongo-cluster
networks:
  mongo-cluster:
    name: "mongo-cluster"